# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

import os

# 获取虚拟环境的site-packages路径
venv_site_packages = '.venv/Lib/site-packages'

yutto_exe = os.path.join(os.getcwd(), '.venv', 'Scripts', 'yutto.exe')
if not os.path.exists(yutto_exe):
    raise FileNotFoundError(f"找不到 yutto.exe: {yutto_exe}")

a = Analysis(
    ['app_launcher.py'],
    pathex=[],
    binaries=[
        (yutto_exe, '.'),
    ],
    datas=[
        ('config_clean/*', 'config'),
        ('scripts', 'scripts'),
        ('routers', 'routers'),
        ('main.py', '.'),
        (os.path.join(venv_site_packages, 'pyecharts/datasets'), 'pyecharts/datasets'),
        (os.path.join(venv_site_packages, 'pyecharts/render/templates'), 'pyecharts/render/templates'),
        (os.path.join(venv_site_packages, 'yutto'), 'yutto'),
        (os.path.join(venv_site_packages, 'faster_whisper/assets'), 'faster_whisper/assets'),
        (os.path.join(venv_site_packages, 'faster_whisper'), 'faster_whisper'),
        # 添加requirements.txt中所有依赖的相关模块
        (os.path.join(venv_site_packages, 'uvicorn'), 'uvicorn'),
        (os.path.join(venv_site_packages, 'fastapi'), 'fastapi'),
        (os.path.join(venv_site_packages, 'qrcode'), 'qrcode'),
        (os.path.join(venv_site_packages, 'requests'), 'requests'),
        (os.path.join(venv_site_packages, 'jieba'), 'jieba'),
        (os.path.join(venv_site_packages, 'pydantic'), 'pydantic'),
        (os.path.join(venv_site_packages, 'numpy'), 'numpy'),
        (os.path.join(venv_site_packages, 'sklearn'), 'sklearn'),
        (os.path.join(venv_site_packages, 'scikit_learn-1.5.2.dist-info'), 'scikit_learn-1.5.2.dist-info'),
        (os.path.join(venv_site_packages, 'snownlp'), 'snownlp'),
        (os.path.join(venv_site_packages, 'yaml'), 'yaml'),
        (os.path.join(venv_site_packages, 'schedule'), 'schedule'),
        (os.path.join(venv_site_packages, 'pandas'), 'pandas'),
        (os.path.join(venv_site_packages, 'openpyxl'), 'openpyxl'),
        (os.path.join(venv_site_packages, 'pymysql'), 'pymysql'),
        (os.path.join(venv_site_packages, 'urllib3'), 'urllib3'),
        (os.path.join(venv_site_packages, 'httpx'), 'httpx'),
        (os.path.join(venv_site_packages, 'aiohttp'), 'aiohttp'),
        (os.path.join(venv_site_packages, 'jinja2'), 'jinja2'),
        (os.path.join(venv_site_packages, 'pyecharts'), 'pyecharts'),
        (os.path.join(venv_site_packages, 'PIL'), 'PIL'),
        (os.path.join(venv_site_packages, 'yutto'), 'yutto'),
        (os.path.join(venv_site_packages, 'faster_whisper/assets'), 'faster_whisper/assets'),
        (os.path.join(venv_site_packages, 'faster_whisper'), 'faster_whisper'),
        (os.path.join(venv_site_packages, 'dateutil'), 'dateutil'),
        (os.path.join(venv_site_packages, 'psutil'), 'psutil'),
        (os.path.join(venv_site_packages, 'tqdm'), 'tqdm'),
        (os.path.join(venv_site_packages, 'email_validator'), 'email_validator'),
    ],
    hiddenimports=[
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pydantic',
        'scripts',
        'routers',
        'numpy',
        'pandas',
        'PIL',
        'jieba',
        'main',
        'asyncio',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'jinja2.ext',
        'scipy',
        'pyecharts',
        'pyecharts.charts',
        'pyecharts.components',
        'pyecharts.options',
        'pyecharts.globals',
        'pyecharts.commons.utils',
        'pyecharts.charts.basic_charts.bar',
        'pyecharts.charts.basic_charts.pie',
        'pyecharts.charts.basic_charts.line',
        'pyecharts.charts.basic_charts.scatter',
        'pyecharts.charts.basic_charts.heatmap',
        'pyecharts.charts.basic_charts.funnel',
        'pyecharts.charts.basic_charts.effectscatter',
        'pyecharts.charts.composite_charts.page',
        'pyecharts.charts.composite_charts.timeline',
        'pyecharts.charts.composite_charts.grid',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.types',
        'starlette.routing',
        'starlette.websockets',
        'scipy.special.cython_special',
        'scipy.sparse.csgraph._validation',
        # requirements.txt中所有依赖
        'qrcode',
        'requests',
        'jieba',
        'pydantic',
        'numpy',
        'sklearn',
        'sklearn.cluster',
        'sklearn.cluster.k_means_',
        'sklearn.utils',
        'sklearn.utils.extmath',
        'sklearn.preprocessing',
        'sklearn.metrics',
        'snownlp',
        'yaml',
        'schedule',
        'pandas',
        'openpyxl',
        'pymysql',
        'urllib3',
        'httpx',
        'aiohttp',
        'jinja2',
        'pyecharts',
        'PIL',
        'yutto',
        'dateutil',
        'psutil',
        'tqdm',
        'email_validator',
        'faster_whisper',
        'faster_whisper.audio',
        'faster_whisper.tokenizer',
        'faster_whisper.transcribe',
        'faster_whisper.utils',
        'faster_whisper.vad',
        'faster_whisper.feature_extractor',
        # 以下是fastapi和其他库的子模块
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.responses',
        'fastapi.exceptions',
        'fastapi.encoders',
        'fastapi.utils',
        'fastapi.openapi',
        'fastapi.staticfiles',
        'fastapi.websockets',
        'fastapi.background',
        'fastapi.concurrency',
        'fastapi.security',
        'fastapi.dependency',
        'fastapi.params',
        'python-dateutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        
        
        
        
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BilibiliHistoryAnalyzer_Full',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='BilibiliHistoryAnalyzer_Full',
)