FROM ubuntu:24.04

ARG PROXY=""
ENV all_proxy=${PROXY} \
    http_proxy=${PROXY} \
    https_proxy=${PROXY}

ENV DEBIAN_FRONTEND=noninteractive

# Install ffmpeg
RUN apt-get update --fix-missing || apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV UV_LINK_MODE=copy
COPY --from=ghcr.io/astral-sh/uv:0.6.12 /uv /uvx /bin/
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

CMD ["uv", "run", "main.py"]
